
# cargo-vet audits file

[[audits.embedded-mcu-hal]]
who = "Felipe Balbi <febalbi@microsoft.com>"
criteria = "safe-to-run"
version = "0.1.0"

[[audits.supports-unicode]]
who = "Felipe Balbi <febalbi@microsoft.com>"
criteria = "safe-to-deploy"
version = "3.0.0"
